# Generated by Django 4.1 on 2022-08-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wukong_fitness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, verbose_name=' '),
        ),
        migrations.AddField(
            model_name='equipment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='equipment',
            name='tags',
            field=models.CharField(blank=True, default=' ', max_length=100),
        ),
    ]
