# Generated by Django 4.1 on 2022-08-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wukong_fitness', '0002_alter_equipment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
