# Generated by Django 4.1 on 2022-08-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wukong_fitness', '0002_equipment_description_equipment_price_equipment_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First', models.CharField(max_length=20)),
                ('Last', models.CharField(default=' ', max_length=50)),
                ('Age', models.IntegerField(default=0, max_length=2)),
                ('Email', models.EmailField(default=' ', max_length=200)),
            ],
        ),
    ]
