# Generated by Django 4.1 on 2022-08-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wukong_fitness', '0004_alter_coaches_age_alter_coaches_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=20)),
                ('last', models.CharField(default=' ', max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('email', models.EmailField(blank=True, default=' ', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Coaches',
        ),
    ]
