# Generated by Django 4.1 on 2022-08-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wukong_fitness', '0004_alter_equipment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='tags',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
