# Generated by Django 4.1 on 2022-08-27 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wukong_fitness', '0005_coach_delete_coaches'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='coach',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='coach',
            old_name='first',
            new_name='First',
        ),
        migrations.RenameField(
            model_name='coach',
            old_name='last',
            new_name='Last',
        ),
    ]
